sudo: false


language: node_js


cache:
  directories:
    - node_modules


node_js:
  - '8'
  - 'stable'


install:
  - npm install


before_script:
  - npm prune


script:
  - npm test


after_success:
  - npm run coverage


deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
